### ISSUE TITLE
Notes from Meeting October 20 2020

### ISSUE THREAD

**Issue by ZoeLeBlanc** [jrladd/network_navigator#5]
notes from the meeting:
- [x] resize graphs and ~animate between them~
- [x] distribution graphs for metrics
- [x] csv add header to input (and additional logic)
- [x] separate out javascript files with package json
- [x] add code to download png
- [x] download metrics csv
- [x] use responsive svg
- [x] make dev branch

**Comment by ZoeLeBlanc** [comment]
For responsive svg, have the panels resize if the other is collapsed. Also for visualization panel allow scrollable.

**Comment by ZoeLeBlanc** [comment]
graph customization:
- directed graph should automatically have arrows and line thickness for weights
- color system (scheme picker? monochromatic, color blind, )
- node size by centrality measures
- node grey out on click
- node toggle label but show text on click

**Comment by ZoeLeBlanc** [comment]
- fix headers in datatables
- read in potential header from data entry area

**Comment by jrladd** [comment]
Just a note: the datatables header thing wound up being complicated, so I'm saving that for a separate commit. You can go ahead and merge your stuff in; I'll fix that later.
